UI_TEXTS = {
    'ko': {
        'window_title': '영상/이미지 업스케일러',
        'tab_image': '이미지 업스케일',
        'tab_video': '비디오 업스케일',
        'tab_video_merge': '영상 병합',
        'tab_remove_bg': "배경 제거",
        'browse': '찾아보기',
        'model_select_tip': 'src/weights 안의 모델 중 하나를 선택하세요.',
        'output_folder': '출력 폴더:',
        'output_folder_tip': '결과물이 저장될 폴더를 선택합니다.',
        'device_label': '시스템 정보:',
        'input_image': '입력 이미지:',
        'input_image_tip': '업스케일할 이미지 파일을 선택하세요.',
        'upscale_image': '이미지 업스케일 시작',
        'model_select': '모델 선택:',
        'tile_size': '타일 크기:',
        'tile_size_tip': 'VRAM이 부족할 경우 타일 크기를 낮추세요.',
        'input_video': '입력 비디오:',
        'input_video_tip': '업스케일할 영상 파일을 선택하세요.',
        'run_video_upscale': '비디오 업스케일 시작',
        'split_count': '분할 개수:',
        'split_count_tip': '영상을 여러 파트로 나누어 처리합니다.',
        'target_parts': '대상 파트:',
        'target_parts_tip': '처리할 파트 번호를 입력하세요 (예: 0~9).',
        'input_folder': '입력 폴더:',
        'input_folder_tip': '합칠 영상 조각들이 들어있는 폴더를 선택하세요.',
        'audio_file': '오디오 파일:',
        'audio_file_tip': '배경음악 또는 원본 오디오를 선택하세요.',
        'select_folder': '폴더 선택',
        'select_audio': '오디오 선택',
        'clear_audio': '초기화',
        'work_list': '🎬 작업 목록',
        'run_merge': '영상 병합 실행',
        'menu_theme': '테마',
        'menu_light': '라이트 모드',
        'menu_dark': '다크 모드',
        'menu_language': '언어',
        'lang_ko': '한국어',
        'lang_en': '영어',
        'cpu_recommend': '[CPU 모드] {0} 사용 중. 2x 권장 및 분할 개수를 높이세요.',
        'igpu_recommend': '[Intel QSV 가속] {0} 사용 중. 2x 권장, 타일 200~400 조절.',
        'gpu_recommend_high': 'GPU: {0} - 권장: 2x/4x 사용, 타일 400~600 권장.',
        'gpu_recommend_mid': 'GPU: {0} - 권장: 2x 사용, 타일 200~300 권장.',
        'gpu_recommend_low': 'GPU: {0} - 권장: 2x 사용, 타일 100~200 권장.',
        'log_ffmpeg_start': "⏳ FFmpeg가 없어 다운로드를 시작합니다...",
        'log_extracting': "📦 압축 해제 중",
        'log_ffmpeg_error': "❌ FFmpeg 설치 오류: {}",
        'log_ffmpeg_ready': "✅ FFmpeg 준비 완료",
        'log_ffmpeg_fail': "❌ FFmpeg 초기 준비 실패",
        'log_downloading_model': "⏳ {} 다운로드 중...",
        'log_download_complete': "✅ 다운로드 완료",
        'log_converting_model': "🔄 Intel GPU 가속 모델 변환 중 ({}x{})...",
        'log_convert_complete': "✅ 변환 완료: {}",
        'log_convert_fail': "❌ 변환 실패: {}",
        'log_upscale_complete': "✨ 업스케일 완료",
        'log_error': "❌ 오류: {}",
        'log_device_info': "🚀 가속 장치: {}",
        'log_model_info': "📦 모델: {}",
        'log_res_optimized': "✅ 해상도 최적화 완료: {}x{}",
        'log_parts_saved' : '📁 파트 {} 저장 완료',
        'log_fatal_error': "🛑 하드웨어 오류로 인해 작업을 즉시 중단합니다.",
        'log_part_start': "🎬 파트 {}/{} 시작 (프레임 {}~{})",
        'log_merge_start': "🔄 모든 파트 병합 및 오디오 합성 시작...",
        'log_audio_source': "🔊 소리 소스: {}",
        'log_audio_none': "🔊 소리 선택 해제 (무음 병합)",
        'log_merge_fail': "❌ 병합 실패",
        'lang_name': "한국어",
        'log_lang_changed': "🌐 언어가 변경되었습니다: {}",
        'err_input_title': '입력 오류',
        'err_input_msg': '입력 파일을 선택해주세요.',
        'err_part_title': '입력 오류',
        'err_part_msg': '대상 파트 형식이 올바르지 않습니다. (예: 0~9)',
        'log_files_found': '📁 {0}개 파일을 순서대로 찾았습니다.',
        'log_file_item': ' -> {0}',
        'warn_no_video_title': '경고',
        'warn_no_video_msg': '해당 폴더에 영상 파일이 없습니다.',
        'warn_no_folder_title': '경고',
        'warn_no_folder_msg': '먼저 병합할 폴더를 선택해주세요.',
        'save_dialog_title': '결과 저장',
        'save_dialog_filter': 'MP4 파일 (*.mp4);;TS 파일 (*.ts)',
        'log_merge_success': '✅ 완료: {0}',
        'log_merge_fail': '❌ 실패: {0}',
        'msg_merge_success_title': '완료',
        'msg_merge_success_text': '영상 병합이 성공적으로 끝났습니다.',
        'msg_merge_fail_title': '오류',
        'msg_merge_fail_text': '병합 중 오류가 발생했습니다: {0}',
        'log_convert_success': '✅ 변환 완료: {0}',
        'log_convert_fail': '❌ 변환 실패: {0}',
        'log_unknown_opt_warn': '알 수 없는 최적화 경고',
        'log_file_replace_fail': '❌ 파일 교체 실패: {0}',
        'log_intel_convert': '🔄 Intel GPU 가속 모델 변환 중 (Scale x{0})...',
        'log_download_complete': '✅ 다운로드 완료',
        'err_conn_title': '연결 오류',
        'err_conn_text': '다운로드 실패 (Time-out)',
        'err_conn_info': '네트워크 문제로 모델을 다운로드할 수 없습니다.\n\n오류 내용: {0}\n\n프로그램을 다시 실행해주세요.',
        'audio_select_title': '오디오 파일 선택',
        'audio_select_filter': '오디오 파일 (*.mp3 *.wav *.aac *.m4a);;영상 파일 (*.mp4 *.mov *.avi *.mkv)',
        'log_audio_source': '🎵 오디오 소스 설정됨: {0}',
        'rbg_start_btn' : '배경 제거 실행',
        'log_rbg_ready': "✅ 배경 제거 모델 준비 완료",
        'log_total_frames': "🎬 총 {0} 프레임 분석 시작",
        'log_processing_frame': "⏳ 처리 중: {2}% ({0}/{1} 프레임)",
        'rbg_start_btn': "배경 제거 시작",
        'log_rbg_ready': "✅ 배경 제거 모델 준비 완료",
    },
    'en': {
        'window_title': 'Image/Video Upscaler',
        'tab_image': 'Image Upscale',
        'tab_video': 'Video Upscale',
        'tab_video_merge': 'Video Auto Merge',
        'tab_remove_bg': "Remove BG",
        'browse': 'Browse',
        'model_select_tip': 'Please select one of the models in src/weights.',
        'output_folder': 'Output Folder:',
        'output_folder_tip': 'Select output folder.',
        'device_label': 'System Info:',
        'input_image': 'Input Image:',
        'input_image_tip': 'Select image to upscale.',
        'upscale_image': 'Start Image Upscale',
        'model_select': 'Select Model:',
        'tile_size': 'Tile Size:',
        'tile_size_tip': 'Lower tile size if VRAM is low.',
        'input_video': 'Input Video:',
        'input_video_tip': 'Select video to upscale.',
        'run_video_upscale': 'Start Video Upscale',
        'split_count': 'Split Count:',
        'split_count_tip': 'Splits video for parallel processing.',
        'target_parts': 'Target Parts:',
        'target_parts_tip': 'Enter parts (e.g., 0~9).',
        'input_folder': 'Input Folder:',
        'input_folder_tip': 'Select folder with video parts.',
        'audio_file': 'Audio File:',
        'audio_file_tip': 'Select audio file.',
        'select_folder': 'Select Folder',
        'select_audio': 'Select Audio',
        'clear_audio': 'Reset',
        'work_list': '🎬 Work List',
        'run_merge': 'Run Merge',
        'menu_theme': 'Theme',
        'menu_light': 'Light Mode',
        'menu_dark': 'Dark Mode',
        'menu_language': 'Language',
        'lang_ko': 'Korean',
        'lang_en': 'English',
        'cpu_recommend': '[CPU Mode] {0}. 2x recommended.',
        'igpu_recommend': '[Intel QSV] {0}. 2x recommended, tile 200~400.',
        'gpu_recommend_high': 'GPU: {0} - 2x/4x, tile 400~600 recommended.',
        'gpu_recommend_mid': 'GPU: {0} - 2x, tile 200~300 recommended.',
        'gpu_recommend_low': 'GPU: {0} - 2x, tile 100~200 recommended.',
        'log_ffmpeg_start': "⏳ FFmpeg not found. Starting download...",
        'log_extracting': "📦 Extracting files...",
        'log_ffmpeg_error': "❌ FFmpeg installation error: {}",
        'log_ffmpeg_ready': "✅ FFmpeg Ready",
        'log_ffmpeg_fail': "❌ FFmpeg initial preparation failed",
        'log_downloading_model': "⏳ Downloading {}: ",
        'log_download_complete': "✅ Download Complete",
        'log_converting_model': "🔄 Converting to Intel GPU model (Scale x{})...",
        'log_convert_complete': "✅ Conversion Complete: {}",
        'log_convert_fail': "❌ Conversion Failed: {}",
        'log_upscale_complete': "✨ Upscale Completed",
        'log_error': "❌ Error: {}",
        'log_device_info': "🚀 Device: {}",
        'log_model_info': "📦 Model: {}",
        'log_res_optimized': "✅ Resolution Optimized: {}x{}",
        'log_parts_saved' : '📁 Part {} saved',
        'log_fatal_error': "🛑 Task stopped immediately due to hardware error.",
        'log_part_start': "🎬 Part {}/{} Start (Frame {}~{})",
        'log_merge_start': "🔄 Starting merge of all parts and audio synthesis...",
        'log_audio_source': "🔊 Audio source: {}",
        'log_audio_none': "🔊 No audio (Muted merge)",
        'log_merge_fail': "❌ Merge failed",
        'lang_name': "English",
        'log_lang_changed': "🌐 Language changed to: {}",
        'err_input_title': 'Input Error',
        'err_input_msg': 'Please select an input file.',
        'err_part_title': 'Input Error',
        'err_part_msg': 'Invalid target part format. (e.g., 0~9)',
        'log_files_found': '📁 Found {0} files in order.',
        'log_file_item': ' -> {0}',
        'warn_no_video_title': 'Warning',
        'warn_no_video_msg': 'No video files found in the folder.',
        'warn_no_folder_title': 'Warning',
        'warn_no_folder_msg': 'Please select a folder to merge first.',
        'save_dialog_title': 'Save Result',
        'save_dialog_filter': 'MP4 Files (*.mp4);;TS Files (*.ts)',
        'log_merge_success': '✅ Success: {0}',
        'log_merge_fail': '❌ Failed: {0}',
        'msg_merge_success_title': 'Success',
        'msg_merge_success_text': 'Video merge completed successfully.',
        'msg_merge_fail_title': 'Error',
        'msg_merge_fail_text': 'An error occurred during merge: {0}',
        'log_convert_success': '✅ Conversion completed: {0}',
        'log_convert_fail': '❌ Conversion failed: {0}',
        'log_unknown_opt_warn': 'Unknown optimization warning',
        'log_file_replace_fail': '❌ File replacement failed: {0}',
        'log_intel_convert': '🔄 Converting model for Intel GPU acceleration (Scale x{0})...',
        'log_download_complete': '✅ Download complete',
        'err_conn_title': 'Connection Error',
        'err_conn_text': 'Download Failed (Time-out)',
        'err_conn_info': 'Cannot download model due to network issues.\n\nError: {0}\n\nPlease restart the program.',
        'audio_select_title': 'Select Audio File',
        'audio_select_filter': 'Audio Files (*.mp3 *.wav *.aac *.m4a);;Video Files (*.mp4 *.mov *.avi *.mkv)',
        'log_audio_source': '🎵 Audio source set: {0}',
        'rbg_start_btn' : 'Start Remove Background',
        'log_rbg_ready': "✅ Remove Background Model Ready",
        'log_total_frames': "🎬 Starting analysis of {0} total frames",
        'log_processing_frame': "⏳ Processing: {2}% ({0}/{1} frames)",
        'rbg_start_btn': "Start Background Remove",
        'log_rbg_ready': "✅ Background remove Model ready",
    }   
}